nome = input("Olá, eu sou um BOT, como te chamas?")
print("Dou-te as boas vindas",nome)
idade = input("Quantos anos tens?")
print("Fantástico,já tens”,",idade ,"anos")
cidade = input("És de onde?")
print("Uau", cidade ,"? Nunca visitei!")